TAG=app
IMAGE_NAME=$DOCKERHUB_LOGIN/$DOCKERHUB_REPOSITORY
IMAGE_NAME_BUILDNUM=$IMAGE_NAME:${CIRCLE_BUILD_NUM}
IMAGE_NAME_LATEST=$IMAGE_NAME:latest

docker build -t $TAG .
docker tag $TAG $IMAGE_NAME_BUILDNUM
docker tag $TAG $IMAGE_NAME_LATEST

echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin

docker push $IMAGE_NAME_BUILDNUM
docker push $IMAGE_NAME_LATEST
