version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
        auth:
          username: anthonyjhoiro
          password: $DOCKERHUB_PASSWORD 

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run: 
          name: Install deps using Yarn
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

